### ISSUE TITLE
Error: Cannot find module 'node_modules\tailwindcss\lib\util\processPlugins'

### ISSUE THREAD

**Issue by Pika-Pool** [tqwewe/prettier-plugin-tailwind#48]
**Describe the bug**
Getting the following error on running prettier after installing the plugin.
```
Error: Cannot find module 'D:\DEV\js-ts\codedamn\1-quiz-app\node_modules\tailwindcss\lib\util\processPlugins'
Require stack:
- D:\DEV\js-ts\codedamn\1-quiz-app\node_modules\tailwind-classes-sorter\lib\index.js
- D:\DEV\js-ts\codedamn\1-quiz-app\node_modules\prettier-plugin-tailwind\lib\index.js
- D:\DEV\js-ts\codedamn\1-quiz-app\node_modules\prettier-plugin-tailwind\prettier-plugin-tailwind.js
- D:\DEV\js-ts\codedamn\1-quiz-app\node_modules\prettier\index.js
- D:\DEV\js-ts\codedamn\1-quiz-app\node_modules\prettier\bin-prettier.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new TWClassesSorter (D:\DEV\js-ts\codedamn\1-quiz-app\node_modules\tailwind-classes-sorter\lib\index.js:28:31)
    at Object.<anonymous> (D:\DEV\js-ts\codedamn\1-quiz-app\node_modules\prettier-plugin-tailwind\lib\index.js:10:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\DEV\\js-ts\\codedamn\\1-quiz-app\\node_modules\\tailwind-classes-sorter\\lib\\index.js',
    'D:\\DEV\\js-ts\\codedamn\\1-quiz-app\\node_modules\\prettier-plugin-tailwind\\lib\\index.js',
    'D:\\DEV\\js-ts\\codedamn\\1-quiz-app\\node_modules\\prettier-plugin-tailwind\\prettier-plugin-tailwind.js',
    'D:\\DEV\\js-ts\\codedamn\\1-quiz-app\\node_modules\\prettier\\index.js',
    'D:\\DEV\\js-ts\\codedamn\\1-quiz-app\\node_modules\\prettier\\bin-prettier.js'
  ]
```

**To Reproduce**
1. `npm i prettier prettier-plugin-tailwind tailwindcss -D` 
2. create `index.html` file in `src` folder
2. `npx prettier -c src`

**Expected behavior**
No error

**Versions:**
 - prettier-plugin-tailwind version: 2.2.12
 - prettier version: 2.5.1
 - Operating system: Windows 10
 - NPM/Yarn version: npm v8,1,2

**Comment by nezzard** [comment]
Same error

**Comment by cereallarceny** [comment]
Same thing with me. Same versions of prettier and plugin as well.

**Comment by seawatts** [comment]
+1

**Comment by JosephAnson** [comment]
Install the tailwindlabs offical version instead, this project is no longer supported.

https://github.com/tailwindlabs/prettier-plugin-tailwindcss/
